### ISSUE TITLE
[Mod] Fixed Screen Ratio & Add Board Title & Saved Alert - jeonmmingu

### ISSUE THREAD

**Issue by jeonmmingu** [prgmr99/Trello-clone#10]
- ### **New Issue**

1. Add board 마지막 Alert의 Saved를 한국어로 바꿔주실 수 있나요?
2. 화면 크기 비율 100%에 맞춰서 수정해주세요 plz..
3. 이름을 입력해주세요 + 보드 이름 -> "보드 이름을 입력해주세요" 로 교체해주세요 :)

**Comment by prgmr99** [comment]
1번과 3번은 너무 Easy한 내용이라 빠르게 바꿔 드렸습니다.
하지만, 2번은 문제가 있습니다. 2번을 수정하다보니 새로운 문제가 수면 위로 올라왔습니다.
그래서 그 문제도 같이 수정해서 올리겠습니다.

**Comment by prgmr99** [comment]
2번의 비율은 고쳤습니다. 2번의 수정하면 생긴 추가적은 issues를 올리겠습니다.
